### ISSUE TITLE
[Wording] official contact mail-address for conformity assessment

### ISSUE THREAD

**Issue by moedn** [oho-wiki/WP1-Alpha-version#12]
Our wording so far:

- applicant
- application
- review
- reviewer
- review result
- conformity assessment
- conformity assessment body
- attestation
- complaint

For the official contact mail we had discussed and created validate@oho.wiki \
After a call with Robert we came to the point that "validation" isn't the right term to use in this context. We cannot "validate" OSH documentation as we would validate e.g. a certain model or method in research projects.

A summary of available suggestions:

- assessment@oho.wiki
- conformity@oho.wiki
- certus@oho.wiki
- audit@oho.wiki
- attestation@oho.wiki

I personally prefer confirmity@oho.wiki\
assessment@oho.wiki would also work, but I fear misspelling when people try to reach us.

↓
This issue is to be decided **by Wednesday, 06.05 18h** (hopefully once forever) as we really need this mail address now :)

**Comment by timmwille** [comment]
as short and multilingual as possible: audit@oho.wiki is the only option that fits in my oppinion

**Comment by oho-wiki** [comment]
wenn die "ofizielle Bezeichnung" des Projektes assessment bzw. assessment platform ist, würde ich assessment@oho.wiki nehmen, um das wording so einheitlich wie möglich zu gestalten

**Comment by DeniseBryson** [comment]
assessment@oho.wiki was the only thing I understood right away.

**Comment by moedn** [comment]
discussion is closed. **assessment@oho.wiki** won :)
